### ISSUE TITLE
Invited users can not access the wiki until ACL rules are created

### ISSUE THREAD

**Issue by pchampin** [ndarilek/dokuwiki-sandstorm#3]
When I created a DokuWiki grain, its ACL configuration was empty, and this prevented the users I had invited to access to the wiki.

This was solved by creating a rule for @user in the wiki.

The user experience would be smoother if that rule was created by default...

**Comment by zeigerpuppy** [comment]
Thanks, worked this out,

Anonymous users viewing the page from a "get sharable link" URL can see the docs.
if @All group is marked for "read" access

I agree with @pchampin, it would be great if these mappings were available by default and matched the sandstorm privilege categories

**Comment by ndarilek** [comment]
I would accept a PR to implement that, otherwise I'll hopefully get to 
it soon. Sorry folks, overtaxed right now. :(

**Comment by ndarilek** [comment]
Should be fixed now. Thanks for reporting!

**Comment by mgax** [comment]
@ndarilek the Sandstorm app market says about DokuWiki "Last update: October 26, 2016", so it doesn't include this fix? If so, could you please make a new release? This bug just bit us a couple of times recently.
