### ISSUE TITLE
Publishing to URL

### ISSUE THREAD

**Issue by zeigerpuppy** [ndarilek/dokuwiki-sandstorm#7]
It would be really great to be able to publish to a URL in the same way that the ghost port does.

**Comment by ndarilek** [comment]
Closing as out of scope for this app. Sorry, it isn't meant as a static publishing app and would require significant change to make it so. You can use the upcoming Sandstorm standalone grain feature to publish at a specific domain.

**Comment by zeigerpuppy** [comment]
thanks for the explanation, for those interested, here's some discussion on the standalone rain feature:
https://groups.google.com/forum/#!topic/sandstorm-dev/XyF9gWYQYU0
