### ISSUE TITLE
View-only sharable link not functional

### ISSUE THREAD

**Issue by zeigerpuppy** [ndarilek/dokuwiki-sandstorm#8]
An anonymous user browsing to a shareable sandstorm link cannot access the site.

They see a "Permission Denied" error

```
No ACL setup yet! Denying access to everyone.

Permission Denied
Sorry, you don't have enough rights to continue.
```

**Comment by ndarilek** [comment]
Thanks for reporting. Closing as a duplicate of #3. Please track/submit changes there.
